name: Upload Python Package

on:
  push:
#    branches:
#      - main
    tags:
      - "v*.*.*"

jobs:
  release-build:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry Action
        # You may pin to the exact commit or the version.
        # uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b
        uses: snok/install-poetry@v1.3.4
        with:
          # The Poetry version to install
          version: 1.6.1
      - name: build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          poetry build
      - name: upload windows dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    environment: release
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
