# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Poetry Action
      # You may pin to the exact commit or the version.
      # uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b
      uses: snok/install-poetry@v1.3.4
      with:
        # The Poetry version to install
        version: 1.6.1
    - name: Test with pytest
      run: |
        pytest
